name: proyecto_movil_2
description: "App de Gestión de Emergencias con Localización en Tiempo Real"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # === ICONOS ===
  cupertino_icons: ^1.0.8

  # === FIREBASE CORE ===
  firebase_core: ^4.2.1
  
  # === FIREBASE AUTHENTICATION ===
  firebase_auth: ^6.1.2
  
  # === CLOUD FIRESTORE (Base de datos) ===
  cloud_firestore: ^6.1.0
  
  # === FIREBASE STORAGE (Almacenar fotos) ===
  firebase_storage: ^13.0.4
  
  # === AUTENTICACIÓN CON GOOGLE ===
  google_sign_in: ^7.2.0
  
  # === GOOGLE MAPS ===
  google_maps_flutter: ^2.5.3
  
  # === GPS / LOCALIZACIÓN ===
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # === CÁMARA Y GALERÍA ===
  image_picker: ^1.0.7
  
  # === MANEJO DE ESTADO ===
  provider: ^6.1.1
  
  # === FORMATO DE FECHAS ===
  intl: ^0.20.2
  
  # === GENERAR IDs ÚNICOS ===
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true